ALTER TABLE children
ADD COLUMN IF NOT EXISTS level_up_bonuses_received INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pet_fed_total INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pet_happy_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS savings_deposits INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS savings_goals_met INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gifts_made INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gold_pot_fixes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gold_pot_unbroken_days INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS manual_deductions INTEGER DEFAULT 0;
